MyProject/urls.py
from django.contrib import admin
from django.urls import path

from MyApp import views as v

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', v.LandingPageView.as_view(), name="landing-page"),
    path('add_donation/', v.AddDonationView.as_view(), name="add-donation"),
    path('success/', v.AddDonationConfirmationView.as_view(), name="form-confirmation"),
    path('register/', v.RegisterView.as_view(), name="register"),
    path('login/', v.LoginView.as_view(), name="login"),
    path('logout/', v.LogoutView.as_view(), name="logout"),
    path('profile/', v.UserProfileView.as_view(), name="user-profile"),
    path('your_donations/', v.UserDonationView.as_view(), name="user-donations"),
    path('profile/modify/', v.UserProfileModifyView.as_view(), name="user-profile-modify"),
    path('profile/confirm/', v.UserProfileModifyAccessView.as_view(), name="user-profile-modify-access"),
    path('confirmation/', v.UserConfirmationsView.as_view(), name="user-confirmation"),
    path('verify/<slug:link>/', v.UserRegisterVerifyActivateLinkView.as_view(), name="verify-activation-link"),
    path('password/remind/', v.UserRemindPasswordView.as_view(), name="remind-password"),
    path('password/reset/<slug:link>/', v.UserPasswordResetView.as_view(), name="reset-password"),

]

MyApp/models.py
import json
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Sum


# Create your models here.

class ExtendedUser(AbstractUser):

    account_is_active = models.BooleanField(default=False)

    @classmethod
    def validate_user_data(cls, email, password):
        user = cls.objects.all().filter(username=email).first()
        if user and user.check_password(password):
            return user

    def save(self, *args, **kwargs):
        super().save()
        if hasattr(self, 'account'):
            self.account.save()
        else:
            self.activation = Account.objects.create(
                activation=self,
                activation_uuid=uuid.uuid4()
            )


class Account(models.Model):

    activation = models.OneToOneField(
        ExtendedUser,
        on_delete=models.CASCADE,
    )

    activation_uuid = models.UUIDField(unique=True, null=True, blank=True)
    reset_password_uuid = models.UUIDField(null=True, blank=True, unique=True)


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Institution(models.Model):

    # Institution type choices.
    class InstitutionTypeChoices(models.IntegerChoices):
        FOUNDATION = 1, 'Fundacja'
        N_GOV_ORGANIZATION = 2, 'Organizacja pozarządowa'
        LOCAL_COLLECTION = 3, 'Zbiórka lokalna'

    # Institution trust assess.
    class InstitutionIsTrustedChoices(models.IntegerChoices):
        TRUSTED = 1, 'Zaufana'
        UNTRUSTED = 0, 'Niezaufana'

    name = models.CharField(max_length=128)
    description = models.TextField()

    type = models.IntegerField(
        choices=InstitutionTypeChoices.choices,
        default=InstitutionTypeChoices.FOUNDATION
    )

    categories = models.ManyToManyField(Category)

    is_trusted = models.IntegerField(
        choices=InstitutionIsTrustedChoices.choices,
        default=0
    )

    @classmethod
    def query_set_to_json(cls, query_set):
        data = []
        [data.append(
            {'name': query.name,
             'description': f'Cel i misja: {query.description}',
             'categories': query.display_all_categories(),
             'type': query.type,
             }
        ) for query in query_set]
        return json.dumps(data)

    def display_all_categories(self):
        categories = self.categories.all()
        if not categories:
            return 'Przyjmiemy każdą pomoc.'
        return ', '.join([cat.name for cat in categories])

    def accepted_donations_id(self):
        return [category.pk for category in self.categories.all()]

    def __str__(self):
        return self.name


class Donation(models.Model):

    # Pick up status.
    class DonationPickUpStatusChoices(models.IntegerChoices):
        PICKED_UP = 1, 'Odebrana'
        NOT_PICKED_UP = 0, 'Nieodebrana'

    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=64)
    phone_number = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    post_code = models.CharField(max_length=64)
    pick_up_date = models.DateField(null=True, blank=True)
    pick_up_time = models.TimeField(null=True, blank=True)
    pick_up_remarks = models.TextField(null=True, blank=True)

    is_taken = models.IntegerField(
        choices=DonationPickUpStatusChoices.choices,
        default=0
    )

    archive_date = models.DateTimeField(null=True, blank=True)

    user = models.ForeignKey(
        ExtendedUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    @classmethod
    def quantity_sum(cls):
        bags = cls.objects.all().aggregate(q_sum=Sum('quantity'))['q_sum']
        return bags if bags else 0

    @classmethod
    def count_supported_institutions(cls):
        return cls.objects.all().count()

    def __str__(self):
        return self.institution

MyApp/views.py
import datetime
import pprint

import uuid

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.password_validation import validate_password

from django.core.paginator import Paginator
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect

from django.utils.http import urlsafe_base64_decode
from django.views import View

from django.core.exceptions import ObjectDoesNotExist, ValidationError

from MyApp import models as m
from MyApp.email_module import EmailTemplates
from MyApp import contact_form_handler


# Create your views here.


class LandingPageView(View):
    def get(self, request):
        cls = m.Donation
        institutions = m.Institution.objects.all()

        items_per_page = 2

        # Filter to extract all types of institutions.
        institutions_dict = {

            1: Paginator(institutions.filter(type=1), items_per_page),

            2: Paginator(institutions.filter(type=2), items_per_page),

            3: Paginator(institutions.filter(type=3), items_per_page),
        }

        page = request.META.get('HTTP_CURRENT_PAGE', None)
        if page:
            institution_type = int(request.META.get('HTTP_INSTITUTION_TYPE', 1))
            query_set = institutions_dict[institution_type].get_page(page)
            data = m.Institution.query_set_to_json(query_set)
            return JsonResponse(data, safe=False)

        # Handle contact form.
        if contact_form_handler.send(
            request,
            m.ExtendedUser,
            EmailTemplates,
            settings.EMAIL_HOST_USER
        ):
            return redirect('user-confirmation')

        context = {
            'bags': cls.quantity_sum(),
            'institutions_count': cls.count_supported_institutions(),

            'foundations': institutions_dict[1].get_page(1),
            'foundations_pages': institutions_dict[1].page_range,

            'n_gov_organizations': institutions_dict[2].get_page(1),
            'organization_pages': institutions_dict[2].page_range,

            'local_collections': institutions_dict[3].get_page(1),
            'collections_pages': institutions_dict[3].page_range,
        }

        return render(request, 'MyApp/index.html', context=context)


class AddDonationView(LoginRequiredMixin, View):
    login_url = settings.LOGIN_URL

    def get(self, request):
        categories = m.Category.objects.all()
        institutions = m.Institution.objects.all()
        context = {
            'categories': categories,
            'institutions': institutions,
        }

        return render(request, 'MyApp/form.html', context=context)

    def post(self, request):

        # User provided data.
        data = request.POST
        quantity = data.get('bags', 1)
        categories = data.getlist('categories')
        institution = m.Institution.objects.get(id=data.get('organization'))
        address = data.get('address')
        phone_number = data.get('phone')
        city = data.get('city')
        post_code = data.get('postcode')
        pick_up_date = data.get('data')
        pick_up_time = data.get('time')
        pick_up_remarks = data.get('more_info')

        try:
            donation = m.Donation.objects.create(
                quantity=quantity,
                institution=institution,
                address=address,
                phone_number=phone_number,
                city=city,
                post_code=post_code,
                pick_up_date=pick_up_date,
                pick_up_time=pick_up_time,
                pick_up_remarks=pick_up_remarks,
                user=request.user
            )
            donation.categories.set(categories)
            donation.save()
        except (ValidationError, ValueError):
            return redirect('landing-page')

        return redirect('form-confirmation')


class AddDonationConfirmationView(View):
    def get(self, request):
        context = {
            'display_donation': True
        }
        return render(request, 'MyApp/form-confirmation.html', context=context)


class LoginView(View):
    def get(self, request):
        context = {
            'display_login_register_navbar': True
        }
        return render(request, 'MyApp/login.html', context=context)

    def post(self, request):
        data = request.POST
        email = data.get('email')
        password = data.get('password')
        if user := m.ExtendedUser.validate_user_data(email, password):

            if not user.account_is_active:

                msg = """Konto nie zostalo aktywowane. 
                Link zostal przeslany na podany adres e-mail."""

                messages.add_message(request, messages.INFO, msg)
                return redirect('login')

            login(request, user)
            return redirect('landing-page')

        return redirect('register')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('landing-page')


class RegisterView(View):
    def get(self, request):
        context = {
            'display_login_register_navbar': True
        }

        return render(request, 'MyApp/register.html', context=context)

    def post(self, request):
        data = request.POST

        first_name = data.get('name')
        surname = data.get('surname')
        user_email = data.get('email')
        password = data.get('password')
        password2 = data.get('password2')

        error = None
        password_not_equal = None
        try:
            validate_password(password)
        except ValidationError as err:
            error = err

        if password != password2:
            password_not_equal = "Hasla sie roznia."

        if error or password_not_equal:
            messages.add_message(request, messages.ERROR, password_not_equal)
            for e in error:
                messages.add_message(request, messages.ERROR, e)
            return redirect('register')

        if user := m.ExtendedUser.objects.create_user(
            first_name=first_name,
            last_name=surname,
            email=user_email,
            username=user_email,
            password=password,
        ):

            email = EmailTemplates(user.activation.activation_uuid)
            email.send_register_confirmation(
                name=first_name,
                uuid=email.create_activation_link(request),
                to=[user_email]
            )

            msg = """
                    Dziękujemy za rejestracje w naszym serwisie. 
                    Link aktywacyjny zostanie przeslany na podany adres e-mail.
                """

            messages.add_message(request, messages.INFO, msg)

            return redirect('user-confirmation')

        return redirect('register')


class UserProfileView(View):
    def get(self, request):
        return render(request, 'MyApp/user-profile.html')


class UserProfileModifyAccessView(View):
    def get(self, request):
        return render(request, 'MyApp/user-profile-modify-access.html')

    def post(self, request):
        password = request.POST.get('password')
        user = authenticate(username=request.user.username, password=password)
        if user:
            return redirect('user-profile-modify')
        return redirect('landing-page')


class UserProfileModifyView(View):
    def get(self, request):
        return render(request, 'MyApp/user-profile-modify.html')

    def post(self, request):
        data = request.POST

        # User profile data.
        last_name = data.get('last_name')
        first_name = data.get('first_name')
        email = data.get('email')

        # User password.
        user_password_update = {
            'old_password': data.get('old_password'),
            'new_password': data.get('new_password'),
            'new_password2': data.get('new_password2'),
        }
        check_password_string = (
                user_password_update['new_password']
                ==
                user_password_update['new_password2']
        )

        assess_passwords = (
                request.user.check_password(
                    user_password_update['old_password'])
                and check_password_string
        )

        user = request.user
        if any(user_password_update.values()) and assess_passwords:
            user.set_password(user_password_update['new_password'])
            authenticate(request)

        user.last_name = last_name
        user.first_name = first_name
        user.email = email
        user.username = email
        user.save()

        login(request, user)
        return redirect('user-profile-modify')


class UserDonationView(View):
    def get(self, request):
        filter_query = request.GET.get('search')
        donations = request.user.donation_set.all().order_by(
            'is_taken', 'pick_up_date'
        )

        context = {
            'donations': donations.filter(is_taken=filter_query) if filter_query else donations
        }
        return render(request, 'MyApp/user-donations.html', context=context)

    def post(self, request):
        donation = m.Donation.objects.get(id=request.POST.get('donation'))
        donation.is_taken = 1
        donation.archive_date = datetime.datetime.today()
        donation.save()
        return redirect(request.META['HTTP_REFERER'])


class UserConfirmationsView(View):
    def get(self, request):
        return render(request, 'MyApp/emails/email_confirmations.html')


class UserRegisterVerifyActivateLinkView(View):

    def get(self, request, link):
        try:
            rfc_4122_format = urlsafe_base64_decode(link).decode("UTF-8")
            user = m.ExtendedUser.objects.get(
                account__activation_uuid=uuid.UUID(rfc_4122_format)
            )
            user.account_is_active = True

MyApp/templates/MyApp/__base__.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'MyApp/css/style.css' %}" />
  </head>

    <body>
        {% block content %}
        {% endblock %}

        <footer>
            <!-- Include footer -->
            {% include 'MyApp/components/footer_component.html' %}
        </footer>

        <!-- Js Script -->
        <script src="{% static 'MyApp/js/app.js' %}"></script>
    </body>
</html>

MyApp/templates/MyApp/form-confirmation.html
{% extends 'MyApp/__base__.html' %}
    {% block content %}

        <!-- NAVBAR -->
        {% include 'MyApp/components/navbar_component.html' %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

{% endblock %}

MyApp/templates/MyApp/form.html
{% extends 'MyApp/__base__.html' %}
    {% block content %}
    {% load static %}

        <!-- NAVBAR -->
        {% include 'MyApp/components/navbar_component.html' %}
        <script src="{% static 'MyApp/js/form-handler.js' %}"></script>

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section id="donation" class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form id="donation_form" action="" method="post">
            {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>

            {% for category in categories %}
                <div class="form-group form-group--checkbox">
                  <label>
                    <input
                      type="checkbox"
                      name="categories"
                      value="{{ category.pk }}"
                    />
                    <span class="checkbox"></span>
                    <span class="description"
                      >{{ category.name }}</span
                    >
                  </label>
                </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" value="1"/>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>

            {% for institution in institutions %}
                <div class="form-group form-group--checkbox">
                  <label>
                    <input type="hidden" name="accepted_values" value="{{ institution.accepted_donations_id }}">
                    <input type="radio" name="organization" value="{{ institution.pk }}"  />

                    <span class="checkbox radio"></span>
                    <span class="description">
                      <div class="title">{{ institution.name }}</div>
                      <div class="subtitle">
                        Cel i misja: {{ institution.description }}
                      </div>
                    </span>
                  </label>
                </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

{% endblock %}

MyApp/templates/MyApp/login.html
{% extends 'MyApp/__base__.html' %}
    {% block content %}
    <header>

        <!-- NAVBAR -->
        {% include 'MyApp/components/navbar_component.html' %}

    </header>

    <section class="login-page">

        {% if messages %}

            <h2>
                {% for message in messages %}
                {{ message }}
            {% endfor %}
            </h2>

        {% else %}
            <h2>Zaloguj się</h2>
        {% endif %}


      <form action="" method="POST">
      {% csrf_token %}

        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="{% url 'remind-password' %}" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>

      </form>
    </section>

{% endblock %}

MyApp/templates/MyApp/register.html
{% extends 'MyApp/__base__.html' %}
    {% block content %}

        <style>

        section.login-page div.register-errors {
            margin-top: 15px;
            font-size: 1.7rem;
            font-family: 'Open Sans', sans-serif;
            font-weight: 400;
            border-left: 1px solid black;
            padding: 20px;
        }

        </style>
    <header>

        <!-- Login/Register navbar -->
        {% include 'MyApp/components/navbar_component.html' %}

    </header>

    <section class="login-page">
      <h2>Załóż konto</h2>

        <div style="width: 100%; display: flex; justify-content: center">

              <div style="margin-top: 30px;">
              {% if messages %}
                {% for message in messages %}

                  <div class="register-errors">
                    {{ message }}
                  </div>

                  {% endfor %}
              {% endif %}
              </div>

              <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" name="name" placeholder="Imię" />
                </div>
                 <div class="form-group">
                  <input type="text" name="surname" placeholder="Nazwisko" />
                </div>
                <div class="form-group">
                  <input type="email" name="email" placeholder="Email" />
                </div>
                <div class="form-group">
                  <input type="password" name="password" placeholder="Hasło" />
                </div>
                <div class="form-group">
                  <input type="password" name="password2" placeholder="Powtórz hasło" />
                </div>

                <div class="form-group form-group--buttons">
                  <a href="{% url 'login' %}" class="btn btn--without-border">Zaloguj się</a>
                  <button class="btn" type="submit">Załóż konto</button>
                </div>

              </form>
        </div>
    </section>

{% endblock %}

MyApp/templates/MyApp/user-donations.html
{% extends 'MyApp/__base__.html' %}
    {% load static %}
    {% block content %}
        <style>

            footer {
                z-index: -1;
                background-image: url({% static 'static/MyApp/images/header-bg.jpg' %});
                background-position: -50vw;
            }

            div.contact {
                display: none;
            }

            div.bottom-line {
                display: none;
            }

            .user-donations-button {
                border: black 1px solid;
                padding: 15px;
                background: transparent;
                cursor: pointer;
            }

        </style>

        {% include 'MyApp/components/navbar_component.html' %}


        <div class="slogan container container--90" style="justify-content: start; flex-direction: column;">
            <div class="slogan--item">
                <h1>
                    Twoje Darowizny
                </h1>
            </div>

            <form id="filter-donation" action="">
                <div style="font-size: 1.8rem; padding: 5px; margin-bottom: 10px">
                    <button type="submit" class="user-donations-button" value="1" name="search">Odebrane</button>
                    <button type="submit" class="user-donations-button" value="0" name="search">Nieodebrane</button>
                    <a href="{% url 'user-donations' %}"><button class="user-donations-button">Wszystkie</button></a>
                </div>
            </form>


            {% for donation in donations %}
                <div class="slogan--item" style="border: black 1px solid; margin-top: 10px; position: relative">
                    <h1>
                        {{ donation.institution.name }}

                    </h1>

                    <div style="position: absolute; text-align: right;right: 10px; top: 10px; font-size: 2.2rem">Status<br>{{ donation.get_is_taken_display }}</div>


                    {% if donation.is_taken == 0 %}
                        <form id="archive-donation" action="" method="POST" style="position: absolute; top: 10px; left: 10px">
                            {% csrf_token %}
                            <button type="submit" name="donation" value="{{ donation.pk }}" class="user-donations-button" style="font-size: 1.5rem">Archiwizuj</button>
                        </form>
                    {% endif %}

                    <div style="display: flex; justify-content: space-between; font-size: 2.0rem; padding: 0 10px">
                        <span>Liczba workow</span>
                        <span>Kategorie</span>
                        {% if donation.is_taken != 1 %}<span>Data odbioru</span>{% else %}<span>Odebrano dnia</span>{% endif %}
                    </div>

                    <div style="display: flex; justify-content: space-between; font-size: 1.6rem; padding: 10px 20px 10px 20px">
                        <span>{{ donation.quantity }}</span>
                        <div style="margin-left: 15%">
                            {% for category in donation.categories.all %}
                                <span>{{ category.name }}</span>
                            {% endfor %}
                        </div>
                        <span>{{ donation.pick_up_date }}, {{ donation.pick_up_time }}</span>
                    </div>

                </div>

            {% endfor %}

        </div>

    {% endblock %}